data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  myconnection: bW9uZ29kYjovL2JhbXVzZTpwTGpMalV6TEhuTWhPZ1BGd1d3Rm4zTGh5QVN0VVZmU041ZklpaDFiUnFheWRXNVhLUE1YanNEMWUxUGJpZTA1akg5UlF0RjhYZ3dqR2tDWXNSUm5EUT09QGJhbXVzZS5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QGJhbXVzZUA=
apiVersion: v1
kind: Secret
metadata:
  name: bamuseaks
---
data:
  host.master: bW1MRUJLaUd0UnQwT0FobnhzYTRpb3RWcTc4WEJvc0lPTWJXYlgxbXZoQ0RrUHgxd0lsYXNBPT0=
  host.function.default: d3RtTkZlRWNrWGhKRFVRL2RzTi9NSGNmYU9FYVlzc1l1WGMyQ3dXWmVXZXV0YVJxeFozbFFnPT0=
  host.systemKey.default: bmcxVk85eDlKc295YnNDZUQ4a2dpTnRFU3pGVXpWREIxMXhNM01DZzQxTHJtL3ZzUGh2TzNRPT0=
  functions.createadvertisement.default: ZGIxbGR3ZG53aUprVU1DSGVhYXZMQ1R5SWpTYWU4UHFpbmp6RThtSm1OcFZPajZNaDF5SVdnPT0=
  functions.deleteadvertisement.default: bFZmN3F1Ymp4Zk5QMnF4YkR4ZndPa2hVaDJsLzFscjRhVFVxSlVjUHZkbHFOQWRZYWpHTWpnPT0=
  functions.getadvertisement.default: NVFPZVZCa1F1SGRtakVKVm9ubFFkVzlWMGNicmwwc3d2blJ2YXNoYXNhcjRRMWhTcmZseGF3PT0=
  functions.getadvertisements.default: eXRQTmNUSXhCTVB3ZllUNU9MQVNmcVFqRnZiL1dDYUpXdThtVVVzZTlNS09qWkJlL1lrbVNRPT0=
  functions.getpost.default: QXkzR1U4SGQzcWd3RmFBYWt5M1BpWklHeUwvMndQMEtobjg2UHA5QW1tZkQ5S0VkTlNpby9nPT0=
  functions.getposts.default: UWtiZ1ViRjlnQVcweU9JTnEvUlpjZ0dKdE5lcENrb21uUFVhRG9VSmlTd2ZtU3hVUU8yV2RBPT0=
  functions.updateadvertisement.default: WU4zbDZ0Wi9UaXdrYTUxaVBQeHFqbXhQRDVIRnd6VGFhMWdhN2VPQ1A4UjZrRE5ZM0FhbkpBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-bamuseaks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bamuseaks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: bamuseaks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bamuseaks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: bamuseaks-http
spec:
  selector:
    app: bamuseaks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamuseaks-http
  labels:
    app: bamuseaks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamuseaks-http
  template:
    metadata:
      labels:
        app: bamuseaks-http
    spec:
      containers:
      - name: bamuseaks-http
        image: bamuseregi.azurecr.io/myfunc:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-bamuseaks
        envFrom:
        - secretRef:
            name: bamuseaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: bamuseaks-function-keys-identity-svc-act
---

